aMasakiTakahashi/stackoverflow_clone_l

- doc/training/server_1day.md
- web/controller/question/show.ex
- web/controller/question/show_test.exs
> fix http method

- web/controller/question/create.ex
- web/controller/question/helper.ex
- web/controller/question/update.ex
modified:   web/controller/question/create.ex
modified:   web/controller/question/helper.ex
> add create v0.1 : user id, title, body, created at を返します。

- web/controller/question/create.ex
- web/controller/question/helper.ex
- web/controller/question/update.ex
modified:   web/controller/question/create.ex
modified:   web/controller/question/helper.ex
> implement API "update"

- web/controller/question/create.ex
> Fix invalid http method

- web/controller/question/create.ex
- web/controller/question/helper.ex
- web/controller/question/update.ex
> Merge "validation" into hnishi's "create" and "update" APIs

- web/controller/question/update.ex
> 部分変更を有効化。+ Refactoring

- web/controller/answer/create.ex
- web/controller/answer/helper.ex
- web/controller/question/create.ex
- web/controller/question/show.ex
> answer create

- test/web/controller/question/update_test.exs
- web/controller/answer/helper.ex
- web/controller/answer/update.ex
- web/controller/question/create.ex
- web/controller/question/helper.ex
- web/controller/question/update.ex
modified:   web/controller/answer/helper.ex
modified:   web/controller/answer/update.ex
> [add] answer/update.ex

- web/controller/question/index.ex
modified:   web/controller/question/index.ex
> [add] request parameterとしてuser_idが指定された場合は、その指定された値をもつquestionのみを返すように拡張

- doc/training/server_3day.md
- web/controller/answer/index.ex
- web/controller/question/index.ex
> [fix] バグ修正 (user_id が nil の時にも対応)

- test/web/controller/question/update_test.exs
- web/controller/answer/index.ex
- web/controller/answer/update.ex
- web/controller/question/update.ex
modified:   test/web/controller/question/update_test.exs
modified:   web/controller/answer/index.ex
modified:   web/controller/answer/update.ex
> [fix] update.ex

- web/controller/comment/create.ex
> [add] comment/create.ex 

- web/controller/comment/create.ex
- web/controller/vote/create.ex
> [add] vote/create.ex 

- web/controller/comment/create.ex
- web/controller/vote/create.ex
modified:   web/controller/comment/create.ex
modified:   web/controller/vote/create.ex
> [fix] vote/create.ex にlike/dislikeをしていた場合に、dislike/like の投票へ変更可能にした。

- test/web/controller/question/update_test.exs
> [add]test question update

- web/static/pages/QuestionCreationPage.vue
> [add] QuestionCreationPage.vue

- js_test/components/Question.spec.js
- js_test/pages/QuestionCreationPage.spec.js
> [add] createQuestionPage と、そのテストを追加しました。

- web/static/components/Question.vue
- web/static/pages/QuestionDetailPage.vue
modified:   web/static/components/Question.vue
> [add] 質問の編集の実装。

- web/static/components/Answer.vue
- web/static/pages/QuestionDetailPage.vue
modified:   web/static/components/Answer.vue
> [add] Answer の表示

- web/static/components/Answer.vue
- web/static/pages/QuestionDetailPage.vue
modified:   web/static/components/Answer.vue
> [add] Answer の編集（更新）の実装。

- web/static/pages/QuestionDetailPage.vue
> [add] 回答の投稿機能の実装。

- web/static/components/Comment.vue
- web/static/pages/QuestionCreationPage.vue
modified:   web/static/components/Comment.vue
modified:   web/static/pages/QuestionCreationPage.vue
> [add] ログインしていない場合に質問を投稿できないようにした。

- web/static/components/Answer.vue
- web/static/components/Question.vue
view Answer comment and add Answer comment
> [add]view Answer comment and add Answer comment

- web/static/pages/QuestionDetailPage.vue
> [add] ログインしていない場合には、回答できないようにした。

- web/static/components/Answer.vue
- web/static/pages/QuestionDetailPage.vue
modified:   web/static/components/Answer.vue
> [add] Answer の作成日時、ユーザー投稿情報一覧ページのリンクの追加。+ 回答件数の表示。

- web/static/components/Question.vue
modified:   web/static/components/Question.vue
> [add] 質問の作成日時、作成者IDの表示。

- web/static/components/Answer.vue
modified:   web/static/components/Answer.vue
> [add] 回答の編集のvalidation機能追加。

- web/static/components/Question.vue
modified:   web/static/components/Question.vue
> [add] 回答の編集のValidation機能の追加。

- web/static/components/AnswerComment.vue
- web/static/components/Comment.vue
> [add] コメントのユーザーチェック

- web/static/components/Answer.vue
- web/static/components/Comment.vue
- web/static/components/Question.vue
ユーザーログインしてないときにコメントを打てないように
回答編集した時にコメントフォームに入力内容がコピーされるバグ修正
> [add] ユーザーログインチェック&bug fix

- web/static/components/Answer.vue
> [fix] 全角スペースの修正

- web/controller/question/helper.ex
- web/static/components/Answer.vue
- web/static/components/Comment.vue
- web/static/components/Question.vue
> [fix]add question comment & 質問投稿時改行可能にした

- web/static/components/Question.vue
> 質問編集時の改行も可能に

- web/static/components/Answer.vue
- web/static/components/Question.vue
> [fix] UIの改善

- web/controller/answer/helper.ex
- web/static/components/Answer.vue
- web/static/components/Comment.vue
> commentにアニメーションを付けました

- web/static/pages/QuestionDetailPage.vue
- web/static/store.js
modified:   web/static/store.js
> [add] vote 機能の実装。

- web/static/pages/QuestionListPage.vue
- web/static/store.js
modified:   web/static/pages/QuestionListPage.vue
modified:   web/static/store.js
> [add] pagination 機能の実装（仮）。

- web/static/pages/QuestionListPage.vue
- web/static/store.js
> [fix] erase commit

- js_test/pages/QuestionListPage.spec.js
- web/static/components/Question.vue
modified:   js_test/pages/QuestionListPage.spec.js
modified:   web/static/components/Question.vue
> deploy のビルドが通るか検証。

- js_test/components/Question.spec.js
- js_test/pages/QuestionListPage.spec.js
- web/static/components/Question.vue
- web/static/pages/QuestionDetailPage.vue
- web/static/store.js
> [fix] vote 機能の修正。（+ テストコードのコメントアウト）

- web/static/components/Question.vue
- web/static/store.js
> [add] 質問の削除機能の実装。

- web/static/components/Answer.vue
- web/static/pages/QuestionListPage.vue
> 回答の修正の入力領域をtextareaに

- web/static/pages/QuestionListPage.vue
- web/static/store.js
> Pagination UIの改善

- web/static/pages/QuestionListPage.vue
- web/static/store.js
modified:   web/static/pages/QuestionListPage.vue
modified:   web/static/store.js
> [fix] pagination のUI改善。

- web/static/pages/QuestionListPage.vue
> [fix] 範囲の修正。

- test/web/controller/question/index_test.exs
- web/controller/question/index.ex
> [fix] 質問取得API (index.ex) のソートをID順から作成日順に変更。

- web/static/components/Question.vue
- web/static/pages/QuestionListPage.vue
> [add] Question List のページにいいね数の表示。
